### ISSUE TITLE
Jupyterlab

### ISSUE THREAD

**Issue by BBassi** [davidbrochart/ipylayout#7]
I could not get it to work in Jupyterlab.

**Comment by davidbrochart** [comment]
Oh, I'm not sure I even tried in JupyterLab. Do you have some error in the browser console?

**Comment by BBassi** [comment]
![Screenshot 2020-11-03 at 18 14 22](https://user-images.githubusercontent.com/25634627/98024621-795e7980-1e00-11eb-8789-2e7fa2ce5f15.png)

**cat /tmp/jupyterlab-debug-q0r3qzis.log**

Node v11.14.0

Yarn configuration loaded.
> /srv/conda/envs/notebook/bin/npm pack @jupyter-widgets/jupyterlab-manager
npm notice 
npm notice 📦  @jupyter-widgets/jupyterlab-manager@3.0.0-alpha.2
npm notice === Tarball Contents === 
npm notice 1.5kB  LICENSE             
npm notice 380B   lib/index.js        
npm notice 15.3kB lib/manager.js      
npm notice 5.3kB  lib/output.js       
npm notice 7.8kB  lib/plugin.js       
npm notice 3.3kB  lib/renderer.js     
npm notice 862B   lib/semvercache.js  
npm notice 3.3kB  package.json        
npm notice 375B   schema/plugin.json  
npm notice 3.0kB  README.md           
npm notice 277B   lib/index.d.ts      
npm notice 5.9kB  lib/manager.d.ts    
npm notice 1.9kB  lib/output.d.ts     
npm notice 828B   lib/plugin.d.ts     
npm notice 960B   lib/renderer.d.ts   
npm notice 216B   lib/semvercache.d.ts
npm notice === Tarball Details === 
npm notice name:          @jupyter-widgets/jupyterlab-manager                 
npm notice version:       3.0.0-alpha.2                                       
npm notice filename:      jupyter-widgets-jupyterlab-manager-3.0.0-alpha.2.tgz
npm notice package size:  13.9 kB                                             
npm notice unpacked size: 51.2 kB                                             
npm notice shasum:        0f3487bee7926a0bf90252a55efd14b1e4bbf050            
npm notice integrity:     sha512-q7Fo3pXaRpMkB[...]wclSgP4FK05Kw==            
npm notice total files:   16                                                  
npm notice 
jupyter-widgets-jupyterlab-manager-3.0.0-alpha.2.tgz

Fetching URL: https://registry.yarnpkg.com/@jupyter-widgets%2Fjupyterlab-manager
> /srv/conda/envs/notebook/bin/npm pack @jupyter-widgets/jupyterlab-manager@2.0.0
npm notice 
npm notice 📦  @jupyter-widgets/jupyterlab-manager@2.0.0
npm notice === Tarball Contents === 
npm notice 1.5kB  LICENSE             
npm notice 380B   lib/index.js        
npm notice 15.3kB lib/manager.js      
npm notice 5.3kB  lib/output.js       
npm notice 7.8kB  lib/plugin.js       
npm notice 3.3kB  lib/renderer.js     
npm notice 862B   lib/semvercache.js  
npm notice 2.3kB  package.json        
npm notice 375B   schema/plugin.json  
npm notice 2.1kB  README.md           
npm notice 277B   lib/index.d.ts      
npm notice 6.0kB  lib/manager.d.ts    
npm notice 1.9kB  lib/output.d.ts     
npm notice 828B   lib/plugin.d.ts     
npm notice 960B   lib/renderer.d.ts   
npm notice 216B   lib/semvercache.d.ts
npm notice === Tarball Details === 
npm notice name:          @jupyter-widgets/jupyterlab-manager         
npm notice version:       2.0.0                                       
npm notice filename:      jupyter-widgets-jupyterlab-manager-2.0.0.tgz
npm notice package size:  13.3 kB                                     
npm notice unpacked size: 49.4 kB                                     
npm notice shasum:        05ab402833df07aac1ec2c549a1d748b3c303185    
npm notice integrity:     sha512-i+qtbEe//W9Ru[...]Fu0KbkxM9aQXQ==    
npm notice total files:   16                                          
npm notice 
jupyter-widgets-jupyterlab-manager-2.0.0.tgz

Fetching URL: https://registry.yarnpkg.com/@jupyter-widgets%2Fjupyterlab-manager
> /srv/conda/envs/notebook/bin/npm pack @jupyter-widgets/jupyterlab-manager@2.0.0
npm notice 
npm notice 📦  @jupyter-widgets/jupyterlab-manager@2.0.0
npm notice === Tarball Contents === 
npm notice 1.5kB  LICENSE             
npm notice 380B   lib/index.js        
npm notice 15.3kB lib/manager.js      
npm notice 5.3kB  lib/output.js       
npm notice 7.8kB  lib/plugin.js       
npm notice 3.3kB  lib/renderer.js     
npm notice 862B   lib/semvercache.js  
npm notice 2.3kB  package.json        
npm notice 375B   schema/plugin.json  
npm notice 2.1kB  README.md           
npm notice 277B   lib/index.d.ts      
npm notice 6.0kB  lib/manager.d.ts    
npm notice 1.9kB  lib/output.d.ts     
npm notice 828B   lib/plugin.d.ts     
npm notice 960B   lib/renderer.d.ts   
npm notice 216B   lib/semvercache.d.ts
npm notice === Tarball Details === 
npm notice name:          @jupyter-widgets/jupyterlab-manager         
npm notice version:       2.0.0                                       
npm notice filename:      jupyter-widgets-jupyterlab-manager-2.0.0.tgz
npm notice package size:  13.3 kB                                     
npm notice unpacked size: 49.4 kB                                     
npm notice shasum:        05ab402833df07aac1ec2c549a1d748b3c303185    
npm notice integrity:     sha512-i+qtbEe//W9Ru[...]Fu0KbkxM9aQXQ==    
npm notice total files:   16                                          
npm notice 
jupyter-widgets-jupyterlab-manager-2.0.0.tgz

Incompatible extension:
@jupyter-widgets/jupyterlab-manager
Found compatible version: 2.0.0
> /srv/conda/envs/notebook/bin/npm pack @jupyter-widgets/jupyterlab-manager@2.0.0
npm notice 
npm notice 📦  @jupyter-widgets/jupyterlab-manager@2.0.0
npm notice === Tarball Contents === 
npm notice 1.5kB  LICENSE             
npm notice 380B   lib/index.js        
npm notice 15.3kB lib/manager.js      
npm notice 5.3kB  lib/output.js       
npm notice 7.8kB  lib/plugin.js       
npm notice 3.3kB  lib/renderer.js     
npm notice 862B   lib/semvercache.js  
npm notice 2.3kB  package.json        
npm notice 375B   schema/plugin.json  
npm notice 2.1kB  README.md           
npm notice 277B   lib/index.d.ts      
npm notice 6.0kB  lib/manager.d.ts    
npm notice 1.9kB  lib/output.d.ts     
npm notice 828B   lib/plugin.d.ts     
npm notice 960B   lib/renderer.d.ts   
npm notice 216B   lib/semvercache.d.ts
npm notice === Tarball Details === 
npm notice name:          @jupyter-widgets/jupyterlab-manager         
npm notice version:       2.0.0                                       
npm notice filename:      jupyter-widgets-jupyterlab-manager-2.0.0.tgz
npm notice package size:  13.3 kB                                     
npm notice unpacked size: 49.4 kB                                     
npm notice shasum:        05ab402833df07aac1ec2c549a1d748b3c303185    
npm notice integrity:     sha512-i+qtbEe//W9Ru[...]Fu0KbkxM9aQXQ==    
npm notice total files:   16                                          
npm notice 
jupyter-widgets-jupyterlab-manager-2.0.0.tgz

Node v11.14.0

Yarn configuration loaded.
> /srv/conda/envs/notebook/bin/npm pack ipylayout
npm notice 
npm notice 📦  ipylayout@0.1.6
npm notice === Tarball Contents === 
npm notice 55B     css/widget.css  
npm notice 748B    lib/extension.js
npm notice 716.7kB dist/index.js   
npm notice 362B    lib/index.js    
npm notice 1.3kB   lib/plugin.js   
npm notice 534B    lib/version.js  
npm notice 4.2kB   lib/widget.js   
npm notice 2.8kB   package.json    
npm notice 652B    README.md       
npm notice 1.5kB   LICENSE.txt     
npm notice === Tarball Details === 
npm notice name:          ipylayout                               
npm notice version:       0.1.6                                   
npm notice filename:      ipylayout-0.1.6.tgz                     
npm notice package size:  208.8 kB                                
npm notice unpacked size: 728.9 kB                                
npm notice shasum:        6c6c36618e4a770edd07a4bd3832805f8be476c0
npm notice integrity:     sha512-HzQWIvxwQgB2S[...]IOOkR0KtGeDuw==
npm notice total files:   10                                      
npm notice 
ipylayout-0.1.6.tgz

Node v11.14.0

Yarn configuration loaded.
Building jupyterlab assets (build:prod:minimize)
> node /srv/conda/envs/notebook/lib/python3.7/site-packages/jupyterlab/staging/yarn.js install --non-interactive
yarn install v1.21.1
[1/5] Validating package.json...
[2/5] Resolving packages...
warning jupyter-leaflet > leaflet.vectorgrid > vector-tile@1.3.0: This module has moved: please install @mapbox/vector-tile instead
warning jupyter-leaflet > leaflet.vectorgrid > vector-tile > point-geometry@0.0.0: This module has moved: please install @mapbox/point-geometry instead
warning @jupyterlab/fasta-extension > msa > bio.io > request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
warning @jupyterlab/fasta-extension > msa > bio.io > request > har-validator@5.1.5: this library is no longer supported
warning bqplot > popper.js@1.16.1: You can find the new Popper v2 at @popperjs/core, this package is dedicated to the legacy v1
warning bqplot > topojson@1.6.27: Use topojson-client, topojson-server or topojson-simplify directly.
[3/5] Fetching packages...
info fsevents@2.1.3: The platform "linux" is incompatible with this module.
info "fsevents@2.1.3" is an optional dependency and failed compatibility check. Excluding it from installation.
info fsevents@1.2.13: The platform "linux" is incompatible with this module.
info "fsevents@1.2.13" is an optional dependency and failed compatibility check. Excluding it from installation.
[4/5] Linking dependencies...
warning " > @lumino/coreutils@1.5.2" has unmet peer dependency "crypto@1.0.1".
warning "jupyter-leaflet > leaflet.markercluster@1.4.1" has incorrect peer dependency "leaflet@~1.3.1".
[5/5] Building fresh packages...
success Saved lockfile.
Done in 33.34s.

> node /srv/conda/envs/notebook/lib/python3.7/site-packages/jupyterlab/staging/yarn.js yarn-deduplicate -s fewer --fail
yarn run v1.21.1
$ /srv/conda/envs/notebook/share/jupyter/lab/staging/node_modules/.bin/yarn-deduplicate -s fewer --fail
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

> node /srv/conda/envs/notebook/lib/python3.7/site-packages/jupyterlab/staging/yarn.js
yarn install v1.21.1
[1/5] Validating package.json...
[2/5] Resolving packages...
[3/5] Fetching packages...
info fsevents@2.1.3: The platform "linux" is incompatible with this module.
info "fsevents@2.1.3" is an optional dependency and failed compatibility check. Excluding it from installation.
info fsevents@1.2.13: The platform "linux" is incompatible with this module.
info "fsevents@1.2.13" is an optional dependency and failed compatibility check. Excluding it from installation.
[4/5] Linking dependencies...
warning " > @lumino/coreutils@1.5.2" has unmet peer dependency "crypto@1.0.1".
warning "jupyter-leaflet > leaflet.markercluster@1.4.1" has incorrect peer dependency "leaflet@~1.3.1".
[5/5] Building fresh packages...
Done in 12.30s.

> node /srv/conda/envs/notebook/lib/python3.7/site-packages/jupyterlab/staging/yarn.js run build:prod:minimize
yarn run v1.21.1
$ ensure-max-old-space webpack --config webpack.prod.minimize.config.js
child_process.js:660
    throw err;
    ^

Error: Command failed: /srv/conda/envs/notebook/share/jupyter/lab/staging/node_modules/.bin/webpack --config webpack.prod.minimize.config.js
    at checkExecSyncError (child_process.js:639:11)
    at Object.execFileSync (child_process.js:657:15)
    at Object.<anonymous> (/srv/conda/envs/notebook/share/jupyter/lab/staging/node_modules/@jupyterlab/buildutils/lib/ensure-max-old-space.js:38:17)
    at Module._compile (internal/modules/cjs/loader.js:816:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:827:10)
    at Module.load (internal/modules/cjs/loader.js:685:32)
    at Function.Module._load (internal/modules/cjs/loader.js:620:12)
    at Function.Module.runMain (internal/modules/cjs/loader.js:877:12)
    at internal/main/run_main_module.js:21:11
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

JupyterLab failed to build
Traceback (most recent call last):

  File "/srv/conda/envs/notebook/lib/python3.7/site-packages/jupyterlab/debuglog.py", line 47, in debug_logging
    yield

  File "/srv/conda/envs/notebook/lib/python3.7/site-packages/jupyterlab/labextensions.py", line 105, in start
    command=command, app_options=app_options)

  File "/srv/conda/envs/notebook/lib/python3.7/site-packages/jupyterlab/commands.py", line 460, in build
    command=command, clean_staging=clean_staging)

  File "/srv/conda/envs/notebook/lib/python3.7/site-packages/jupyterlab/commands.py", line 661, in build
    raise RuntimeError(msg)

RuntimeError: JupyterLab failed to build

Exiting application: jupyter

**Comment by BBassi** [comment]
I tried installing it on the Jupyterlab via binder here: https://jupyter.org/try

**Comment by davidbrochart** [comment]
I'm not sure you can install it from within JupyterLab, have you tried following [these instructions](https://github.com/davidbrochart/ipylayout/blob/master/README.md#installation) in the console?

**Comment by BBassi** [comment]
Yes - no joy
